name: MATLAB CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MATLAB
      uses: mathworks/setup-matlab@v1

    - name: Run tests
      run: matlab -batch "run('tests/test_sum_two_values.m')"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: results
